apiVersion: apps/v1
kind: Deployment
metadata:
  name: plateform-app-production
  namespace: production
  labels:
    app: plateform-app
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plateform-app
      environment: production
  template:
    metadata:
      labels:
        app: plateform-app
        environment: production
    spec:
      containers:
      - name: plateform-app
        image: your-registry.com/plateform-app:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
